CREATE SCHEMA IF NOT EXISTS `education` DEFAULT CHARACTER SET utf8;

USE `education`;

CREATE TABLE IF NOT EXISTS `education`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `slug` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `price` TINYINT UNSIGNED NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `slug`)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8;

CREATE TABLE IF NOT EXISTS `education`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `name`)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8;

CREATE TABLE IF NOT EXISTS `education`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `username` VARCHAR(12) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `email`, `username`)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8;

CREATE TABLE IF NOT EXISTS `education`.`instructors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `username` VARCHAR(12) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `email`, `username`)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8;

CREATE TABLE IF NOT EXISTS `education`.`coordinators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `username` VARCHAR(12) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `email`, `username`)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8;